# dataset name
dataset: 'tiny200'
# create imbalanced data
# select imb_type and imb_factor
imb_type: 'exp'
imb_factor: 0.01
rand_number: 0
workers: 4
# model backbone
backbone: 'resnet18'
# model classifier
classifier: 'dot_product_classifier'
# Training related parameters
gpu: 0
start_epoch: 0
epochs: 300
batch_size: 1024
optimizer: 'sgd'
learning_rate: 0.1
momentum: 0.9
weight_decay: 2e-4
# Remix hyper parameter
k_majority: 3
tau: 0.5
# MAMix hyper parameter
mamix_ratio: -0.25
# logging related
print_freq: 10
root_log: 'log_tiny200'
# root_model: 'checkpoint_tiny200'
# M2m hyper parameter
warm: 250
# reweight: True
beta: 0.9999
num_classes: 200
# loss_type: 'CE' # choices=['CE', 'Focal', 'LDAM']
attack_iter: 10
step_size: 0.1
lam: 0.5
gamma: 0.9
ratio: 100
eff_beta: 1
over: True
imb_start: 5
data_augment: None
sampling  : 'WeightedFixedBatchSampler'
# Path configurations for Tiny-ImageNet-200
tiny_root: /home/maitanha/vgu/lightweight/example/data
train_root: /home/maitanha/vgu/lightweight/example/data/tiny-imagenet-200/tiny-imagenet-200/train
val_root: /home/maitanha/vgu/lightweight/example/data/tiny-imagenet-200/tiny-imagenet-200/val/images