# dataset name
dataset: 'cinic10'
# create imbalanced data
# select imb_type and imb_factor
imb_type: 'exp'
imb_factor: 0.01
rand_number: 0
workers: 4
# model backbone
backbone: 'resnet18'
# model classifier
classifier: 'dot_product_classifier'
# Training related parameters
gpu: 0
start_epoch: 0
epochs: 200
batch_size: 1024
optimizer: 'sgd'
learning_rate: 0.1
momentum: 0.9
weight_decay: 2e-4
# Remix hyper parameter
k_majority: 3
tau: 0.5
# MAMix hyper parameter
mamix_ratio: -0.25
# logging related
print_freq: 10
root_log: 'log_cinic10'
# root_model: 'checkpoint_cinic10'
# M2m hyper parameter
warm: 160
# reweight: True
beta: 0.9999
num_classes: 10
# loss_type: 'CE' # choices=['CE', 'Focal', 'LDAM']
attack_iter: 10
step_size: 0.1
lam: 0.5
gamma: 0.9
ratio: 100
eff_beta: 1
over: True
imb_start: 5
cinic_root : './data'
# sampling method WeightedRandomBatchSampler, WeightedFixedBatchSampler, Random, StratifiedSampler
#sampling  : WeightedRandomBatchSampler #date :4/10
sampling : 'WeightedRandomBatchSampler'
#hyperparameter for balance sampling
n_batches : 179
alpha : 0.5
kind : 'fixed'
data_augment : None
cinic_root: /home/maitanha/vgu/lightweight/example/data/
train_dir: /home/maitanha/vgu/lightweight/example/data/cinic-10/train
val_dir : /home/maitanha/vgu/lightweight/example/data/cinic-10/valid
test_dir : /home/maitanha/vgu/lightweight/example/data/cinic-10/test